/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e6fd3e8a-61cf-4ae4-8bc8-3dd18124994e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kknXSynGv",
    "aws_user_pools_web_client_id": "8bco2ncempdjpfbp2c8tohb0c",
    "oauth": {
        "domain": "fbreactauth9fd3d3e9-9fd3d3e9-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
